export const WHITE_TEXT_COLOR = '#FFFFFF';

export const PADDING_VERTICAL_MULTIPLIER = 0.5;
export const PADDING_HORIZONTAL_MULTIPLIER = 0.75;

export const SHADOW_OPACITY_MULTIPLIER = 0.5; 
export const SHADOW_RADIUS_MULTIPLIER = 0.5;
export const TEXT_HELPER_MULTIPLIER = 0.78;
export const MAT_ICON_MULTIPLIER = 2.3;