export const WHITE_TEXT_COLOR = '#FFFFFF';

export const PADDING_VERTICAL_MULTIPLIER = 0.5;
export const PADDING_HORIZONTAL_MULTIPLIER = 0.75;

export const ICON_MULTIPLIER = 1.5;
export const MAT_ICON_MULTIPLIER = 2.3;
export const ICON_SEPARATOR_WIDTH = 1;

export const LABEL_MARGIN_BOTTOM_MULTIPLIER = 0.4;

export const CHECK_CONTAINER_SIZE_MULTIPLIER = 1.5;

export const ACTION_CONTAINER_SIZE_MULTIPLIER = 1.4;
export const ACTION_CONTAINER_SIZE_MATERIAL_MULTIPLIER = 2.3;

export const TEXT_HELPER_MULTIPLIER = 0.78;
export const TEXT_HELPER_MARGIN_TOP_MULTIPLIER = 0.25;

export const SHADOW_OPACITY_MULTIPLIER = 0.5; 
export const SHADOW_RADIUS_MULTIPLIER = 0.5;