name: Format Check

on:
  pull_request:
    paths:
      - 'npm-packages/**'

jobs:
  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./npm-packages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'npm-packages/**/package.json'

      - name: Install dependencies
        run: npm install

      - name: Run format script
        run: |
          npm run format
          git diff --exit-code

      - name: Run lint script
        run: npm run lint