name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

- name: NPM install, dependencies, build, and test
  working-directory: ./documentation
  run: |
    npm install
    npm run build --if-present
